version: '3'
services:
  # Web server
  webserver:
    build:
      context: ./webserver/
      dockerfile: Dockerfile
      args:
        - mode
        - project_id
    container_name: webserver
    restart: unless-stopped
    tty: true
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - ENV=${ENV}
    ports:
      - "8080:8080"
    volumes:
      - ../.env:/.env
      - ..:/usr/share/nginx/project
    networks:
      - app-network

  # Backoffice server
  boserver:
    build:
      context: ./boserver/
      dockerfile: Dockerfile
      args:
        - mode
        - project_id
    container_name: boserver
    restart: unless-stopped
    tty: true
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - ENV=${ENV}
    ports:
      - "8081:8081"
    volumes:
      - ../.env:/.env
      - ..:/usr/share/nginx/project
    networks:
      - app-network

  # Web server
  proxyserver:
    build:
      context: ./proxy-server/
      dockerfile: Dockerfile
      args:
        - mode
        - project_id
    container_name: proxyserver
    restart: unless-stopped
    tty: true
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - ENV=${ENV}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../.env:/.env
    networks:
      - app-network
    depends_on:
      - webserver
      - boserver

# Docker Networks
networks:
  app-network:
    driver: bridge
